import type {AxiosInstance, InternalAxiosRequestConfig, AxiosResponse} from "axios";

export function installLoggingInterceptor(instance: AxiosInstance) {
    instance.interceptors.request.use((c: InternalAxiosRequestConfig) => {
        const logHeaders = { ...c.headers };
        if (c.data instanceof FormData) {
            (logHeaders as any)['Content-Type'] = 'multipart/form-data (auto-generated by axios)';
        }

        console.debug(`[HTTP] → ${c.method?.toUpperCase()} ${c.baseURL}${c.url}`, {
            headers: logHeaders,
            params: c.params,
            data: c.data
        });
        return c;
    });
    instance.interceptors.response.use((r: AxiosResponse) => {
        console.debug(`[HTTP] ← ${r.status} ${r.config.method?.toUpperCase()} ${r.config.url}`, r.data);
        return r;
    }, (err) => {
        const {config, response} = err || {};
        console.debug(`[HTTP] ⨯ ${response?.status ?? "ERR"} ${config?.method?.toUpperCase()} ${config?.url}`, response?.data ?? err?.message);
        return Promise.reject(err);
    });
}
