name: CI & Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build/publish'
        required: true
        default: 'main'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build-publish:
    name: Build & Publish (Node 22)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (ensure dist)
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance
